[general]
# working_directory = "$HOME"

[window]
dimensions = { columns = 140, lines = 45 }
opacity = 0.96

[scrolling]
history = 100000

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
size = 12